export const actionTypes = {
    CORRECT_GUESS: 'CORRECT_GUESS',
    NEW_GAME: 'NEW_GAME',
    GUESS_WORD: 'GUESS_WORD',
    CLEAR_GUESS_WORDS: 'CLEAR_GUESS_WORDS',
    SET_SECRET_WORD: 'SET_SECRET_WORD'
};